services:
  - type: web
    name: calcom
    env: node
    repo: https://github.com/bonar111/cal.com-asystentai
    branch: main
    buildCommand: |
      yarn install
      NODE_OPTIONS="--max-old-space-size=2048" yarn build
    startCommand: node server.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calcom-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://calcom.onrender.com
      - key: NEXT_PUBLIC_API_V2_URL
        value: https://calcom.onrender.com/api/v2
      - key: NEXT_PUBLIC_APP_URL
        value: https://calcom.onrender.com
      - key: NEXT_PUBLIC_WEBAPP_URL
        value: https://calcom.onrender.com
      - key: NEXT_PUBLIC_BASE_URL
        value: https://calcom.onrender.com
      - key: POSTGRES_PRISMA_URL
        fromDatabase:
          name: calcom-db
          property: connectionString
      - key: POSTGRES_URL_NON_POOLING
        fromDatabase:
          name: calcom-db
          property: connectionString
      - key: POSTGRES_URL
        fromDatabase:
          name: calcom-db
          property: connectionString
      - key: REDIS_URL
        value: redis://not-used
      - key: CALENDSO_ENCRYPTION_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: MAIL_FROM
        value: test@example.com
      - key: SMTP_HOST
        value: smtp.example.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: fakeuser
      - key: SMTP_PASSWORD
        value: fakepassword

databases:
  - name: calcom-db
    plan: free
    databaseName: calcom
    user: caluser
